// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 mxx1.cn
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Reflection;

namespace Mxx1Toolbox
{
    /// <summary>16x16 button icons. A real PNG wins (assets\icons\&lt;id&gt;.png, or the path given
    /// by the manifest); when it is missing the icon is drawn, so the wall always looks complete
    /// even before the icon pack is generated.</summary>
    internal static class IconFactory
    {
        private static readonly Dictionary<string, Image> Cache = new Dictionary<string, Image>(StringComparer.OrdinalIgnoreCase);
        private static readonly Dictionary<string, Image> MutedCache = new Dictionary<string, Image>(StringComparer.OrdinalIgnoreCase);
        private static readonly object Gate = new object();
        private const int IconWidth = 16;
        private const int SourceHeight = 16;   // every source is normalised to 16x16 first
        private const int IconHeight = 15;     // ... and then trimmed, see Normalize

        private static readonly Color[] Palette = new Color[]
        {
            Color.FromArgb(0x2E, 0x74, 0xB5),
            Color.FromArgb(0x1B, 0x9E, 0x74),
            Color.FromArgb(0xC0, 0x50, 0x4D),
            Color.FromArgb(0x8E, 0x6F, 0xB0),
            Color.FromArgb(0xD1, 0x8A, 0x2A),
            Color.FromArgb(0x2A, 0x8C, 0x8C),
            Color.FromArgb(0x9A, 0x5F, 0xB0),
            Color.FromArgb(0x5B, 0x7C, 0x99)
        };

        public static Image Get(ToolItem tool)
        {
            if (tool == null) { return null; }
            lock (Gate)
            {
                Image cached;
                if (Cache.TryGetValue(tool.Id, out cached)) { return cached; }
                Image img = LoadEmbedded(tool);
                if (img == null) { img = LoadPng(tool.IconPath); }
                if (img == null) { img = Normalize(DrawFallback(tool)); }
                Cache[tool.Id] = img;
                return img;
            }
        }

        /// <summary>The muted (grey) twin of a button icon, used by buttons whose feature is not
        /// wired up yet: same canvas, same shape, but desaturated and lifted towards white, so the
        /// whole button reads as "not available yet" while staying exactly as tall as the real
        /// icon (swapping it in cannot move the label).</summary>
        public static Image GetMuted(ToolItem tool)
        {
            if (tool == null) { return null; }
            lock (Gate)
            {
                Image cached;
                if (MutedCache.TryGetValue(tool.Id, out cached)) { return cached; }
                Image source = Get(tool);
                if (source == null) { return null; }
                Bitmap bmp = new Bitmap(source.Width, source.Height);
                for (int y = 0; y < source.Height; y++)
                {
                    for (int x = 0; x < source.Width; x++)
                    {
                        Color c = ((Bitmap)source).GetPixel(x, y);
                        if (c.A == 0) { bmp.SetPixel(x, y, Color.Transparent); continue; }
                        // Rec.601 luma, then mixed 45% towards white: grey but not black.
                        int grey = (c.R * 299 + c.G * 587 + c.B * 114) / 1000;
                        int lifted = grey + (255 - grey) * 45 / 100;
                        if (lifted > 255) { lifted = 255; }
                        bmp.SetPixel(x, y, Color.FromArgb(c.A, lifted, lifted, lifted));
                    }
                }
                MutedCache[tool.Id] = bmp;
                return bmp;
            }
        }

        /// <summary>Icons generated by tools\Make-Icons.ps1 are embedded as icons.&lt;id&gt;.png, so the
        /// exe stays a single file. A PNG dropped next to the exe is only used when the manifest
        /// does not name an explicit icon file.</summary>
        private static Image LoadEmbedded(ToolItem tool)        {
            if (!string.IsNullOrEmpty(tool.Icon)) { return null; }
            try
            {
                Assembly asm = Assembly.GetExecutingAssembly();
                using (Stream s = asm.GetManifestResourceStream("icons." + tool.Id + ".png"))
                {
                    if (s == null) { return null; }
                    return Normalize(Image.FromStream(s));
                }
            }
            catch
            {
                return null;
            }
        }

        /// <summary>Normalises a raw source image to the button icon canvas: 16 wide, 15 tall,
        /// with the drawing on the top rows.
        ///
        /// A flat button paints its image one pixel below the centre of the label's line box, so a
        /// 16px tall canvas lands one pixel lower than the button centre. Measured on the rendered
        /// window (30px button, 8.25pt label): the canvas sat on rows 8..23 -- centre 15.5 against a
        /// button centre of 14.5 -- and the ink on rows 9..23, centre 16.0, while the label itself
        /// sat on the centre exactly. Every icon we generate has a fully transparent top row, so
        /// dropping that row lifts the drawing onto the label's centre: measured again afterwards,
        /// the ink covers rows 8..22, centre 15.0, within half a pixel of the button centre (the
        /// best an integer canvas can do, because the generated ink is itself half a pixel low
        /// inside its 16px source). The busy spinner goes through here too, so it is exactly as tall
        /// as the icon it replaces and swapping it in cannot move anything.
        ///
        /// A source that already paints into its top row is never trimmed at the top (that would
        /// cut ink) -- rows 0..14 are taken instead, which lands on the same canvas.</summary>
        private static Image Normalize(Image raw)
        {
            if (raw == null) { return null; }
            Bitmap full = new Bitmap(IconWidth, SourceHeight);
            using (Graphics g = Graphics.FromImage(full))
            {
                g.InterpolationMode = InterpolationMode.HighQualityBicubic;
                g.DrawImage(raw, new Rectangle(0, 0, IconWidth, SourceHeight));
            }
            int top = IsRowBlank(full, 0) ? 1 : 0;
            Bitmap canvas = new Bitmap(IconWidth, IconHeight);
            using (Graphics g = Graphics.FromImage(canvas))
            {
                g.Clear(Color.Transparent);
                g.DrawImageUnscaled(full, 0, -top);
            }
            full.Dispose();
            return canvas;
        }

        private static bool IsRowBlank(Bitmap bmp, int row)
        {
            for (int x = 0; x < bmp.Width; x++)
            {
                if (bmp.GetPixel(x, row).A > 8) { return false; }
            }
            return true;
        }

        private static Image _busy;

        /// <summary>A spinner shown while a button is running. It goes through Normalize like every
        /// other icon, so it is exactly as tall as the icon it replaces and swapping it in does not
        /// move the icon or the label by a single pixel.</summary>
        public static Image Busy()
        {
            lock (Gate)
            {
                if (_busy != null) { return _busy; }
                Bitmap bmp = new Bitmap(IconWidth, SourceHeight);
                using (Graphics g = Graphics.FromImage(bmp))
                {
                    g.SmoothingMode = SmoothingMode.AntiAlias;
                    using (Pen ring = new Pen(Color.FromArgb(0x00, 0x78, 0xD7), 2.6f))
                    {
                        ring.StartCap = LineCap.Round;
                        ring.EndCap = LineCap.Round;
                        g.DrawArc(ring, 2.6f, 2.6f, 10.8f, 10.8f, 30f, 275f);
                    }
                    using (SolidBrush dot = new SolidBrush(Color.FromArgb(0x00, 0x78, 0xD7)))
                    {
                        g.FillEllipse(dot, 6.2f, 6.2f, 3.6f, 3.6f);
                    }
                }
                _busy = Normalize(bmp);
                bmp.Dispose();
                return _busy;
            }
        }

        private static Image LoadPng(string path)
        {
            try
            {
                if (string.IsNullOrEmpty(path) || !File.Exists(path)) { return null; }
                using (FileStream fs = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
                {
                    return Normalize(Image.FromStream(fs));
                }
            }
            catch
            {
                return null;
            }
        }

        /// <summary>Rounded square in a colour picked from the id, with the first character on top.
        /// No emoji, no symbol font: 微软雅黑 has no glyph for characters like U+2713.</summary>
        private static Image DrawFallback(ToolItem tool)
        {
            Bitmap bmp = new Bitmap(16, 16);
            Color color = Palette[Math.Abs(StableHash(tool.Id)) % Palette.Length];
            using (Graphics g = Graphics.FromImage(bmp))
            {
                g.SmoothingMode = SmoothingMode.AntiAlias;
                g.TextRenderingHint = System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
                using (GraphicsPath path = RoundedRect(new Rectangle(1, 1, 14, 14), 4))
                using (SolidBrush brush = new SolidBrush(color))
                {
                    g.FillPath(brush, path);
                }
                string text = FirstChar(tool.Name);
                if (text.Length > 0)
                {
                    using (Font font = new Font("Microsoft YaHei", 8f, FontStyle.Bold, GraphicsUnit.Point))
                    using (SolidBrush white = new SolidBrush(Color.White))
                    using (StringFormat sf = new StringFormat())
                    {
                        sf.Alignment = StringAlignment.Center;
                        sf.LineAlignment = StringAlignment.Center;
                        g.DrawString(text, font, white, new RectangleF(1f, 0.5f, 14f, 15f), sf);
                    }
                }
            }
            return bmp;
        }

        private static string FirstChar(string name)
        {
            if (string.IsNullOrEmpty(name)) { return ""; }
            string s = name.Trim();
            if (s.StartsWith("+")) { return "+"; }
            return s.Substring(0, 1).ToUpperInvariant();
        }

        private static int StableHash(string s)
        {
            int h = 17;
            if (s == null) { return h; }
            for (int i = 0; i < s.Length; i++) { h = h * 31 + s[i]; }
            return h;
        }

        private static GraphicsPath RoundedRect(Rectangle r, int radius)
        {
            int d = radius * 2;
            GraphicsPath path = new GraphicsPath();
            path.AddArc(r.X, r.Y, d, d, 180, 90);
            path.AddArc(r.Right - d, r.Y, d, d, 270, 90);
            path.AddArc(r.Right - d, r.Bottom - d, d, d, 0, 90);
            path.AddArc(r.X, r.Bottom - d, d, d, 90, 90);
            path.CloseFigure();
            return path;
        }

        public static void Clear()
        {
            lock (Gate) { Cache.Clear(); MutedCache.Clear(); }
        }
    }
}
